server:
  port: 8181

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://127.0.0.1:8081/oauth2/jwks}
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect